In [44]:
from tensorflow.keras.preprocessing.text import one_hot

In [45]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'you are too good'
]

In [46]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'you are too good']

In [47]:
## Define vocabulary size
voc_size = 10000

In [48]:
##one hot representation for every word
one_hot_rep = [one_hot(words,voc_size) for words in sent]
one_hot_rep

[[1520, 3129, 7984, 1904],
 [1520, 3129, 7984, 3213],
 [1520, 8126, 7984, 9777],
 [7268, 5493, 8231, 9828, 6883],
 [7268, 5493, 8231, 9828, 1362],
 [910, 1520, 9693, 7984, 4426],
 [8805, 3665, 7997, 9828]]

### 'the' feature is represented using one-hot encoding, with the 1521st position set to 1 and all remaining positions set to 0.

In [49]:
## word embedding represntation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [50]:
import numpy as np

In [51]:
'''
We need to make every sentences of equal size so we use pad_sequence and set a max sentence length
addind zeros, post or pre.
'''

sent_length = 8
embedded_docs = pad_sequences(one_hot_rep,padding='pre',maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 1520 3129 7984 1904]
 [   0    0    0    0 1520 3129 7984 3213]
 [   0    0    0    0 1520 8126 7984 9777]
 [   0    0    0 7268 5493 8231 9828 6883]
 [   0    0    0 7268 5493 8231 9828 1362]
 [   0    0    0  910 1520 9693 7984 4426]
 [   0    0    0    0 8805 3665 7997 9828]]


In [52]:
## Feature rep
dim=10


In [53]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.build(input_shape=(None, sent_length))
model.compile('adam','mse')

In [54]:
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [55]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step


array([[[-0.0351783 ,  0.01982442, -0.01328305, -0.00776018,
          0.02672192,  0.01698688,  0.02847374, -0.00996435,
          0.01845118,  0.0034435 ],
        [-0.0351783 ,  0.01982442, -0.01328305, -0.00776018,
          0.02672192,  0.01698688,  0.02847374, -0.00996435,
          0.01845118,  0.0034435 ],
        [-0.0351783 ,  0.01982442, -0.01328305, -0.00776018,
          0.02672192,  0.01698688,  0.02847374, -0.00996435,
          0.01845118,  0.0034435 ],
        [-0.0351783 ,  0.01982442, -0.01328305, -0.00776018,
          0.02672192,  0.01698688,  0.02847374, -0.00996435,
          0.01845118,  0.0034435 ],
        [ 0.03549078,  0.0498765 , -0.01161462, -0.03472283,
         -0.02427243, -0.00633527, -0.01072646,  0.04640486,
          0.01439406,  0.02704616],
        [ 0.01423434, -0.00359214, -0.01284901, -0.04967334,
         -0.00448958, -0.04319072,  0.04104817, -0.01825646,
         -0.0107537 , -0.02546942],
        [ 0.0154433 , -0.0403424 , -0.00134585, -0.0

In [56]:
embedded_docs[0]

array([   0,    0,    0,    0, 1520, 3129, 7984, 1904], dtype=int32)